services:
  postgres:
    image: postgres:16
    container_name: postgres_asset
    restart: always
    environment:
      POSTGRES_USER: asset_user
      POSTGRES_PASSWORD: "12345678."
      POSTGRES_DB: asset_tracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: spring_asset_api
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/asset_tracker
      SPRING_DATASOURCE_USERNAME: asset_user
      SPRING_DATASOURCE_PASSWORD: "12345678."
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  postgres_data:
